name: Android Build
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r25c
      - name: Setup Java JDK

        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.2.5

      - name: Restore Previous Cache
        id: cache-debug-build-android-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
            export/release/android/haxe/
            export/release/android/obj/
          key: cache-android-build

      - name: Installing Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.2.1
          haxelib install openfl 9.2.1
          haxelib install flixel 5.2.2
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 3.0.2
          haxelib install tjson
          haxelib install hxjsonast
          haxelib git hxCodec https://github.com/FNF-Pk-Dev/hxCodec.git
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib install hxcpp-debug-server
          haxelib git extension-androidtools https://github.com/Default-name123/oldtools
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp
          haxelib run lime rebuild hxcpp
          haxelib list

      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set hxCodec git
          haxelib set openfl 9.2.1
          haxelib set lime 8.2.1
          haxelib set flixel 5.2.2
          haxelib set flixel-addons 3.0.2
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Building
        run: haxelib run lime build android -final

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: The Basement Show Android
          path: export/release/android/bin/app/build/outputs/apk/debug
          if-no-files-found: warn
